[project]
name = "primap-datalad-scripts"
version = "0.1.0"
description = "Create, list, delete and manage access to datalad datasets for PRIMAP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.35.71",
    "ruff>=0.8.1",
    "typer>=0.13.1",
]
